# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Netdata
version: "3.1.3"
slug: netdata
description: Netdata - Monitor everything in real time
url: "https://github.com/varuntirumala1/netdata-homeassistant-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
panel_icon: mdi:chart-bell-curve
panel_title: Netdata
ports:
  19999/tcp: 19999
ports:
  19999/tcp: null
ports_description:
  19999/tcp: Web interfacs
map:
  - type: opt
    read_only: False
    path: /config/netdata
hassio_api: true
auth_api: true
docker_api: true
host_network: true
host_pid: true
apparmor: false
journald: true
privileged:
  - SYS_PTRACE
  - SYS_ADMIN
options:
  hostname: homeassistant
  page_cache_size: 32
  dbengine_disk_space: 256
  enable_alarm: true
  enable_log: true
  claim_url: https://app.netdata.cloud
  claim_token: xxxxxxxxxxxxxxxxxxxxxxx
  claim_rooms:
    - ROOM
schema:
  hostname: str
  page_cache_size: int
  dbengine_disk_space: int
  enable_alarm: bool
  enable_log: bool
  claim_url: str
  claim_token: str
  claim_rooms:
    - str
image: "ghcr.io/varuntirumala1/{arch}-netdata-homeassistant-addon"
